# Generated by Django 5.0.4 on 2025-03-25 11:06

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dragon_breath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='quest',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
